name: 'Setup PHP for Github actions'
author: ilyakharev
description: 'GitHub Action for PHP'
inputs:
  php-version:
    description: 'Setup PHP version.'
    default: '8.2'
    required: true
  extensions:
    description: 'Setup PHP extensions.'
    required: false
  ini-file:
    description: 'Set base ini file.'
    default: 'production'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage: 
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false
outputs:
  php-version:
    description: 'PHP version in semver format'
runs:
  using: 'node16'
  main: 'dist/index.js'
